default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bluemine_development

test:
  <<: *default
  database: bluemine_test

production:
  <<: *default
  database: bluemine_production
  username: root
  password: <%= ENV['GGDD_DATABASE_PASSWORD'] %>
